/* USERS */
export const GET_USERS1 = "GET_USERS1"
export const GET_USERS_SUCCESS1 = "GET_USERS_SUCCESS1"
export const GET_USERS_FAIL1 = "GET_USERS_FAIL1"

/* USERS PROFILE */
export const GET_USER_PROFILE1 = "GET_USER_PROFILE1"
export const GET_USER_PROFILE_SUCCESS1 = "GET_USER_PROFILE_SUCCESS1"
export const GET_USER_PROFILE_FAIL1 = "GET_USER_PROFILE_FAIL1"

/**
 * add user
 */
export const ADD_NEW_USER1 = "ADD_NEW_USER1"
export const ADD_USER_SUCCESS1 = "ADD_USER_SUCCESS1"
export const ADD_USER_FAIL1 = "ADD_USER_FAIL1"

/**
 * Edit user
 */
export const UPDATE_USER1 = "UPDATE_USER1"
export const UPDATE_USER_SUCCESS1 = "UPDATE_USER_SUCCESS1"
export const UPDATE_USER_FAIL1 = "UPDATE_USER_FAIL1"

/**
 * Delete user
 */
export const DELETE_USER1 = "DELETE_USER1"
export const DELETE_USER_SUCCESS1 = "DELETE_USER_SUCCESS1"
export const DELETE_USER_FAIL1 = "DELETE_USER_FAIL1"


export const FETCH_GOLDVAULTLIST_SUCCESS1 = 'FETCH_GOLDVAULTLIST_SUCCESS1';
export const FETCH_GOLDVAULTLIST_FAILURE1 = 'FETCH_GOLDVAULTLIST_FAILURE1';
// export const FETCH_GOLDVAULTLIST_REQUEST = 'FETCH_GOLDVAULTLIST_REQUEST';
